name: Docker Image

on:
  push:
    paths:
      - 'pages/**'
      - 'components/**'
      - 'styles/**'
      - 'public/**'
    branches:
      - main


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag tolfixorg/cpg-customer:latest
      - name: Docker push
        run: docker push tolfixorg/cpg-customer:latest